compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
    - current
  libc:
    - glibc
  os:
    - darwin
    - linux
    - current

yarnPath: .yarn/releases/yarn-4.13.0.cjs
